### Get all movies
GET http://localhost:3000/api/movies
Accept: application/json


### Get a movie by id
GET http://localhost:3000/api/movies/1
Accept: application/json


### Create a new movie (VALID)
POST http://localhost:3000/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "Dune",
  "year": 2021
}


### Create a new movie (VALID)
POST http://localhost:3000/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "Matrix",
  "year": 1999
}


### Create a movie (INVALID - missing title)
POST http://localhost:3000/api/movies
Content-Type: application/json
Accept: application/json

{
  "year": 2020
}


### Create a movie (INVALID - wrong year)
POST http://localhost:3000/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "Ancient Movie",
  "year": 1500
}


### Update an existing movie (VALID)
PUT http://localhost:3000/api/movies/1
Content-Type: application/json
Accept: application/json

{
  "title": "Interstellar (Updated)",
  "year": 2014
}


### Update an existing movie (INVALID - missing year)
PUT http://localhost:3000/api/movies/1
Content-Type: application/json
Accept: application/json

{
  "title": "Interstellar Updated Wrong"
}


### Delete a movie
DELETE http://localhost:3000/api/movies/2
Accept: application/json
