### Register admin
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "secret123",
  "role": "admin"
}

### Login admin
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "secret123"
}

### Use token here (replace XXX)
GET http://localhost:4000/items
Authorization: Bearer XXX

### Create event (admin only)
POST http://localhost:4000/items
Authorization: Bearer XXX
Content-Type: application/json

{
  "title": "Exam day",
  "date": "2025-12-18T09:00:00.000Z",
  "location": "TAMK A123",
  "type": "exam"
}
